name: Scheduled Python Script

on:
  schedule:
    - cron: '50 9 * * 1-5'  # 3:20 PM IST (UTC = IST - 5:30)
  workflow_dispatch:       # Allow manual triggering too

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          FYERS_CLIENT_ID: ${{ secrets.FYERS_CLIENT_ID }}
          FYERS_SECRET_ID: ${{ secrets.FYERS_SECRET_ID }}
          FYERS_PIN: ${{ secrets.FYERS_PIN }}
          FYERS_REDIRECT_URI: ${{ secrets.FYERS_REDIRECT_URI }}
          FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
        run: python executor.py
